In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input, Dense, Activation,Dropout
from tensorflow.keras.models import Model

In [3]:
df_train = pd.read_csv("C:/Users/jimmy/Downloads/專案作業二/Concrete_Data.csv")
df_train

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [4]:
# normalize 正規化
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_train1 = scaler.fit_transform(df_train)
df_train2 = pd.DataFrame(df_train1,columns=df_train.columns)
df_train2

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,1.000000,0.000000,0.000000,0.321086,0.077640,0.694767,0.205720,0.074176,0.967485
1,1.000000,0.000000,0.000000,0.321086,0.077640,0.738372,0.205720,0.074176,0.741996
2,0.526256,0.396494,0.000000,0.848243,0.000000,0.380814,0.000000,0.739011,0.472655
3,0.526256,0.396494,0.000000,0.848243,0.000000,0.380814,0.000000,1.000000,0.482372
4,0.220548,0.368392,0.000000,0.560703,0.000000,0.515698,0.580783,0.986264,0.522860
...,...,...,...,...,...,...,...,...,...
1025,0.398174,0.322760,0.451274,0.461661,0.276398,0.200872,0.437280,0.074176,0.522611
1026,0.502740,0.000000,0.577711,0.592652,0.322981,0.049128,0.550426,0.074176,0.359412
1027,0.106164,0.387869,0.542729,0.566294,0.189441,0.265698,0.466633,0.074176,0.266226
1028,0.130365,0.519477,0.000000,0.429712,0.350932,0.548256,0.488961,0.074176,0.379220
1029,0.362785,0.279633,0.391304,0.629393,0.267081,0.184593,0.420221,0.074176,0.374611

In [5]:
X = df_train2.drop('Concrete compressive strength', axis=1)
y = df_train2['Concrete compressive strength']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [14]:
input_layer = Input(shape=(X_train.shape[1],))
dense_layer_1 = Dense(32, activation='relu')(input_layer)
dense_layer_2 = Dense(16, activation='relu')(dense_layer_1)
dense_layer_3 = Dense(8, activation='relu')(dense_layer_2)
output = Dense(1)(dense_layer_3)

model = Model(inputs=input_layer, outputs=output)
model.compile(loss="mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])

In [15]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 8)]               0
_________________________________________________________________
dense (Dense)                (None, 32)                288
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9
=================================================================
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________

In [17]:
history = model.fit(X_train, y_train, batch_size=2, epochs=30, verbose=1, validation_split=0.2)

Epoch 1/30
330/330 [==============================] - 1s 2ms/step - loss: 0.0368 - mean_squared_error: 0.0368 - val_loss: 0.0212 - val_mean_squared_error: 0.0212
Epoch 2/30
330/330 [==============================] - 0s 720us/step - loss: 0.0164 - mean_squared_error: 0.0164 - val_loss: 0.0145 - val_mean_squared_error: 0.0145
Epoch 3/30
330/330 [==============================] - 0s 716us/step - loss: 0.0121 - mean_squared_error: 0.0121 - val_loss: 0.0130 - val_mean_squared_error: 0.0130
Epoch 4/30
330/330 [==============================] - 0s 708us/step - loss: 0.0108 - mean_squared_error: 0.0108 - val_loss: 0.0106 - val_mean_squared_error: 0.0106
Epoch 5/30
330/330 [==============================] - 0s 698us/step - loss: 0.0096 - mean_squared_error: 0.0096 - val_loss: 0.0106 - val_mean_squared_error: 0.0106
Epoch 6/30
330/330 [==============================] - 0s 695us/step - loss: 0.0083 - mean_squared_error: 0.0083 - val_loss: 0.0090 - val_mean_squared_error: 0.0090
Epoch 7/30
330/330 [==============================] - 0s 667us/step - loss: 0.0077 - mean_squared_error: 0.0077 - val_loss: 0.0089 - val_mean_squared_error: 0.0089
Epoch 8/30
330/330 [==============================] - 0s 776us/step - loss: 0.0080 - mean_squared_error: 0.0080 - val_loss: 0.0095 - val_mean_squared_error: 0.0095
Epoch 9/30
330/330 [==============================] - 0s 724us/step - loss: 0.0074 - mean_squared_error: 0.0074 - val_loss: 0.0093 - val_mean_squared_error: 0.0093
Epoch 10/30
330/330 [==============================] - 0s 798us/step - loss: 0.0066 - mean_squared_error: 0.0066 - val_loss: 0.0107 - val_mean_squared_error: 0.0107
Epoch 11/30
330/330 [==============================] - 0s 756us/step - loss: 0.0065 - mean_squared_error: 0.0065 - val_loss: 0.0095 - val_mean_squared_error: 0.0095
Epoch 12/30
330/330 [==============================] - 0s 816us/step - loss: 0.0065 - mean_squared_error: 0.0065 - val_loss: 0.0077 - val_mean_squared_error: 0.0077
Epoch 13/30
330/330 [==============================] - 0s 712us/step - loss: 0.0065 - mean_squared_error: 0.0065 - val_loss: 0.0074 - val_mean_squared_error: 0.0074
Epoch 14/30
330/330 [==============================] - 0s 704us/step - loss: 0.0059 - mean_squared_error: 0.0059 - val_loss: 0.0082 - val_mean_squared_error: 0.0082
Epoch 15/30
330/330 [==============================] - 0s 818us/step - loss: 0.0061 - mean_squared_error: 0.0061 - val_loss: 0.0099 - val_mean_squared_error: 0.0099
Epoch 16/30
330/330 [==============================] - 0s 717us/step - loss: 0.0054 - mean_squared_error: 0.0054 - val_loss: 0.0067 - val_mean_squared_error: 0.0067
Epoch 17/30
330/330 [==============================] - 0s 672us/step - loss: 0.0055 - mean_squared_error: 0.0055 - val_loss: 0.0081 - val_mean_squared_error: 0.0081
Epoch 18/30
330/330 [==============================] - 0s 710us/step - loss: 0.0055 - mean_squared_error: 0.0055 - val_loss: 0.0076 - val_mean_squared_error: 0.0076
Epoch 19/30
330/330 [==============================] - 0s 792us/step - loss: 0.0052 - mean_squared_error: 0.0052 - val_loss: 0.0061 - val_mean_squared_error: 0.0061
Epoch 20/30
330/330 [==============================] - 0s 804us/step - loss: 0.0054 - mean_squared_error: 0.0054 - val_loss: 0.0068 - val_mean_squared_error: 0.0068
Epoch 21/30
330/330 [==============================] - 0s 777us/step - loss: 0.0047 - mean_squared_error: 0.0047 - val_loss: 0.0064 - val_mean_squared_error: 0.0064
Epoch 22/30
330/330 [==============================] - 0s 713us/step - loss: 0.0049 - mean_squared_error: 0.0049 - val_loss: 0.0066 - val_mean_squared_error: 0.0066
Epoch 23/30
330/330 [==============================] - 0s 810us/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0063 - val_mean_squared_error: 0.0063
Epoch 24/30
330/330 [==============================] - 0s 753us/step - loss: 0.0056 - mean_squared_error: 0.0056 - val_loss: 0.0069 - val_mean_squared_error: 0.0069
Epoch 25/30
330/330 [==============================] - 0s 716us/step - loss: 0.0048 - mean_squared_error: 0.0048 - val_loss: 0.0069 - val_mean_squared_error: 0.0069
Epoch 26/30
330/330 [==============================] - 0s 731us/step - loss: 0.0045 - mean_squared_error: 0.0045 - val_loss: 0.0063 - val_mean_squared_error: 0.0063
Epoch 27/30
330/330 [==============================] - 0s 831us/step - loss: 0.0047 - mean_squared_error: 0.0047 - val_loss: 0.0065 - val_mean_squared_error: 0.0065
Epoch 28/30
330/330 [==============================] - 0s 769us/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0060 - val_mean_squared_error: 0.0060
Epoch 29/30
330/330 [==============================] - 0s 739us/step - loss: 0.0044 - mean_squared_error: 0.0044 - val_loss: 0.0059 - val_mean_squared_error: 0.0059
Epoch 30/30
330/330 [==============================] - 0s 722us/step - loss: 0.0044 - mean_squared_error: 0.0044 - val_loss: 0.0078 - val_mean_squared_error: 0.0078

In [18]:
# 預測
df_test_y_predicted = model.predict(X_test)

In [19]:
import numpy as np
from sklearn.metrics import mean_squared_error
print('RMSE为：',np.sqrt(mean_squared_error(y_test,df_test_y_predicted)))

RMSE为： 0.08200791568709237

In [21]:
import scipy
import sklearn
from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_absolute_percentage_error
print('MAPE为：',mean_squared_error(y_test,df_test_y_predicted))

MAPE为： 0.006725298235341251